version: 2
updates:
  # Enable version updates for python
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"

  # Enable version updates for Docker compose
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
  
  # Enable version updates for github actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
