name: Build

inputs:
  poetry-version:
    required: false
    type: string
    default: "1.6.1"

  python-version:
    required: false
    type: string
    default: "3.13"

  poetry-virtualenv:
    required: false
    type: boolean
    default: true

  poetry-virtualenvs-in-project:
    required: false
    type: boolean
    default: true

runs:
  using: "composite"

  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: ${{ inputs.poetry-version }}
        virtualenvs-create: ${{ inputs.poetry-virtualenv }}
        virtualenvs-in-project: ${{ inputs.poetry-virtualenvs-in-project }}

    - name: Cache deps
      id: cache-deps
      uses: actions/cache@v4
      env:
        cache-name: cache-poetry-deps
      with:
        path: .venv
        key: ${{ runner.os }}-poetry-${{ env.cache-name }}-${{ inputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-poetry-${{ env.cache-name }}-${{ inputs.python-version }}-
          ${{ runner.os }}-poetry-${{ env.cache-name }}-

    - name: Install project
      run: poetry install --no-root --no-interaction
      shell: bash
